---

- name: Clone tanks repository
  sudo: yes
  git: repo={{ tanks.deploy.repositories[tanks.deploy.repository] }} dest={{ tanks.path }} version={{ tanks.deploy.version }} force=yes
  when: environment != 'vagrant'
