---

- name: Add nginx.org key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add nginx.org repo
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ precise nginx' state=present
  notify: update apt-cache

- name: Install Nginx Full
  apt: package=nginx-full state=present
  notify: restart nginx

- name: Delete existing default.conf (and back it up)
  file: path=/etc/nginx/conf.d/default.conf state=absent backup=yes

