---

- include: rhel.yml
  when: ansible_os_family in [ 'CentOS', 'RedHat' ]

- include: deb.yml
  when: ansible_os_family in [ 'Ubuntu', 'Debian' ]

- name: Install Nginx.conf Customisations
  sudo: yes
  template: src='nginx.conf.j2' dest='/etc/nginx/conf.d/nginx.conf'

- name: Start nginx
  sudo: yes
  service: name=nginx state=started
