---

- name: Install prerequisites
  sudo: yes
  yum: pkg={{ item }} state=present
  with_items:
    - epel-release
    - libselinux-python

- name: Install packages
  sudo: yes
  yum: pkg={{ item }} state=present
  with_items:
    - nginx
  notify: restart nginx

- name: Delete existing default.conf (and back it up)
  sudo: yes
  file: path=/etc/nginx/conf.d/default.conf state=absent backup=yes

